# apiVersion: v1
# data:
#   rootPassword: {{ .Values.netdetails }}
# kind: ConfigMap
# metadata:
#   name: mysqltest
#   namespace: default
apiVersion: v1
data:
  {{- range $k, $v := .Values.label1 }}
  {{ $k }}_{{ $v.name }} : {{ $v.value }}
  {{- end }}
kind: ConfigMap
metadata:
  name: mysqltest
  namespace: default
  
